name: thebookproject
favicon: null
layout_spectrum: 0.7482034177519381
typography_spectrum: 0.2884723381139338
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.2732040714472532
  lightness: 0.7556365211494267
  saturation: 0.09294130350463092
  rhythmicContrast: 0.939240163192153
purpose: []
