name: thebookproject
favicon: null
layout_spectrum: 0.58261
typography_spectrum: 0.2884723381139338
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#252f30'
    - '#4d6c6e'
    - '#a0b9b6'
    - '#feac3a'
    - '#fee74d'
  brandStrength: 1
  lightness: 0.7556365211494267
  saturation: 0.9375
  rhythmicContrast: 1
purpose: []
